[window]
dynamic_padding = true
opacity = 0.9

[scrolling]
history = 10000

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "0x151515"
foreground = "0xCDCDCD"

[colors.normal]
black = "0x000000"
red = "0xFF2C6D"
green = "0x19F9D8"
yellow = "0xFFB86C"
blue = "0x45A9F9"
magenta = "0xFF75B5"
cyan = "0xB084EB"
white = "0xCDCDCD"

[colors.bright]
black = "0x757575"
red = "0xFF2C6D"
green = "0x19F9D8"
yellow = "0xFFCC95"
blue = "0x6FC1FF"
magenta = "0xFF9AC1"
cyan = "0xBCAAFE"
white = "0xE6E6E6"

[font]
size = 11

[font.normal]
family = "JetBrains Mono NL"

[font.bold]
family = "JetBrains Mono NL"

[font.italic]
family = "JetBrains Mono NL"

[font.bold_italic]
family = "JetBrains Mono NL"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[[mouse.bindings]]
mouse = "Middle"
action = "PasteSelection"

[keyboard]
[[keyboard.bindings]]
key = "Paste"
action = "Paste"

[[keyboard.bindings]]
key = "Copy"
action = "Copy"

[[keyboard.bindings]]
key = "L"
mods = "Control"
action = "ClearLogNotice"

[[keyboard.bindings]]
key = "L"
mods = "Control"
mode = "~Vi"
chars = "\f"

[[keyboard.bindings]]
key = "PageUp"
mods = "Shift"
mode = "~Alt"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "PageDown"
mods = "Shift"
mode = "~Alt"
action = "ScrollPageDown"

[[keyboard.bindings]]
key = "Home"
mods = "Shift"
mode = "~Alt"
action = "ScrollToTop"

[[keyboard.bindings]]
key = "End"
mods = "Shift"
mode = "~Alt"
action = "ScrollToBottom"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "F"
mods = "Control|Shift"
action = "SearchForward"

[[keyboard.bindings]]
key = "B"
mods = "Control|Shift"
action = "SearchBackward"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
mode = "Vi"
action = "ClearSelection"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"
